services:
  db:
    image: postgres
    container_name: auth-matery-db
    restart: always
    ports:
      - 5440:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - auth-db-data:/var/lib/postgresql
  adminer:
    image: adminer
    container_name: auth-mastery-adminer
    restart: always
    ports:
      - 8089:8080
    environment:
      - ADMINER_DESIGN=${DB_THEME}
      - ADMINER_DEFAULT_SERVER=${DB_DEFAULT}

volumes:
  auth-db-data:
